### ISSUE TITLE
Update How to Install Getting Python on Linux notes

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/IntroToPython-2014#115]
slides_sources/source/supplements/python_for_linux.rst

**Comment by PythonCHB** [comment]
Updated -- but I don't have a Linux box handy.

Could someone give this a look-see? 

Also, nice to support Ubuntu, and maybe an rpm-based system too?

**Comment by ranchodeluxe** [comment]
@PythonCHB I've put in a pull request for these changes, just in case you didn't get notified about that

**Comment by PythonCHB** [comment]
looks great -- not closing the issue until we make a decision about ensurepip.

**Comment by ranchodeluxe** [comment]
@PythonCHB : let me look at `ensure-pip` and get back to you, never heard of it. It sounds a little to much like that drink

**Comment by PythonCHB** [comment]
added ensure-pip (without testing) -- I guess we'll find out in class!
