### ISSUE TITLE
Add Maria's email, etc to Session 1 lecture notes

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/IntroToPython-2014#129]
right at the top....

**Comment by PythonCHB** [comment]
@codedragon: at least do this one :-)

**Comment by codedragon** [comment]
I'm on it, just forgot to pull before I edited... Bad Maria, no donut.

**Comment by codedragon** [comment]
Okay, the commits look weird, since I had to do a merge, but it did the right thing.

**Comment by PythonCHB** [comment]
getting close!

Thanks.

On Mon, Oct 5, 2015 at 10:09 PM, codedragon notifications@github.com
wrote:

> Closed #129 https://github.com/UWPCE-PythonCert/IntroToPython/issues/129
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWPCE-PythonCert/IntroToPython/issues/129#event-427560611
> .

## 

Christopher Barker, PhD

Python Language Consulting
- Teaching
- Scientific Software Development
- Desktop GUI and Web Development
- wxPython, numpy, scipy, Cython
