### ISSUE TITLE
Mailman exercise

### ISSUE THREAD

**Issue by codedragon** [UWPCE-PythonCert/IntroToPython-2014#158]
Make sure clear about verifying number/integer input. (not worrying about error handling yet). I think we were meaning that input always returns a string, so student has to make sure they convert it, rather than any actual verification.
Make clear don't need all individual donations, just average and total.

**Comment by PythonCHB** [comment]
I'll go in and clean that up now....

**Comment by PythonCHB** [comment]
Done :-)
